name: CI Workflow

on:
  push:
    branches:
      - main
      - github-actions


jobs: 
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: lint check
        run: npx stylelint "**/*.scss"

  publish_npm:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish
